main: com.gmail.artemis.the.gr8.regenassist.Main
name: RegenAssist
version: 1.0
api-version: 1.18
description: executes the Multiverse regen command for a specific world only
author: Artemis_the_gr8
depend: [Multiverse-Core]
commands:
  regen:
    description: requests a regen for the specified world
    permission: regenassist.regen
    permission-message: §cYou do not have permission to execute this command!
    usage: "/§bregen §a<worldname> §6{keep-seed | §6random-seed | §6supply-seed:§onumber-here} §d[reset-gamerules]"
  regenconfirm:
    description: performs the actual regen for the specified world
    permission: regenassist.regen
    permission-message: §cYou do not have permission to execute this command!
  regenreload:
    description: reloads the config and datafiles
    permission: regenassist.regen
    permission-message: §cYou do not have permission to execute this command!
permissions:
  regenassist.regen:
    description: Allows regen commands
    default: op

